# Generated by Django 5.1.2 on 2024-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_flashcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='flashcard_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_repetition_date',
            field=models.DateField(default='1969-07-20'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_repetition_date',
            field=models.DateField(default='1969-07-20'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetition_number',
            field=models.IntegerField(default=0),
        ),
    ]
