# Generated by Django 5.1.2 on 2024-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0003_rename_flashcard_id_flashcard_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=1, max_length=200),
        ),
    ]
