# Generated by Django 5.1.2 on 2024-11-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0004_flashcard_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='pupil_dilatation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
