# Generated by Django 5.1.2 on 2024-11-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0005_flashcard_pupil_dilatation_alter_flashcard_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilatation', models.FloatField(default=0)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.flashcard')),
            ],
        ),
    ]
