# Generated by Django 5.1.2 on 2024-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0006_pupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='timestamp1',
            field=models.DateField(default='1969-07-20'),
        ),
    ]
